# docker-compose.yml
version: '3.8'

networks:
  lgtm-network:
    driver: bridge

services:
  # Grafana
  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - lgtm-network
    depends_on:
      - loki
      - mimir
      - tempo

  # Loki for logs
  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - lgtm-network

  # Promtail to ship logs to Loki
  promtail:
    image: grafana/promtail:2.8.4
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - lgtm-network
    depends_on:
      - loki

  # Tempo for traces
  tempo:
    image: grafana/tempo:2.1.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"  # Tempo HTTP endpoint
      - "5555:4317"  # OTLP gRPC endpoint on 5555 instead of 4317
    networks:
      - lgtm-network

  # Mimir for metrics
  mimir:
    image: grafana/mimir:2.9.0
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./mimir-config.yaml:/etc/mimir.yaml
    ports:
      - "9009:9009"
    networks:
      - lgtm-network

  # OpenTelemetry Collector as a gateway
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "5555"  # OTLP gRPC on 5555
      - "8889:8889"  # Prometheus metrics exposure
    networks:
      - lgtm-network
    depends_on:
      - tempo
      - loki
      - mimir