multitenancy_enabled: false

api:
  prometheus_http_prefix: /prometheus

server:
  http_listen_port: 9009

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/data/blocks
  bucket_store:
    sync_dir: /tmp/mimir/data/tsdb-sync
  tsdb:
    dir: /tmp/mimir/data/tsdb

compactor:
  data_dir: /tmp/mimir/data/compactor
  sharding_ring:
    kvstore:
      store: inmemory

frontend:
  address: 127.0.0.1
  
store_gateway:
  sharding_ring:
    kvstore:
      store: inmemory