apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
      maxLines: 1000
    version: 1

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags: ['job', 'instance', 'service.name', 'filename']
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: 'mimir'
      traceQuery:
        timeShiftEnabled: true
    version: 1

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    editable: true
    uid: mimir
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
      httpMethod: POST
      prometheusType: Mimir
      cacheLevel: 'High'
      incrementalQuerying: true
    version: 1

  - name: OpenTelemetry Collector Metrics
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    isDefault: false
    editable: true
    uid: otel-metrics
    jsonData:
      httpMethod: POST
      cacheLevel: 'Medium'
    version: 1